fix compatibility issues of kernel code with libbpf submodule

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -1,13 +1,61 @@
-# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
-
 XDP_TARGETS  := xdp_prog_kern
-USER_TARGETS := 
 
-LIBBPF_DIR = ../libbpf/src/
-COMMON_DIR = ../common
+LLC ?= llc
+CLANG ?= clang
+CC ?= gcc
 
-COPY_LOADER := xdp_loader
-COPY_STATS  := xdp_stats
-EXTRA_DEPS := $(COMMON_DIR)/parsing_helpers.h
+XDP_C = ${XDP_TARGETS:=.c}
+XDP_OBJ = ${XDP_C:.c=.o}
 
-include $(COMMON_DIR)/common.mk
+LIBBPF_DIR ?= ../libbpf/src/
+OBJECT_LIBBPF = $(LIBBPF_DIR)/libbpf.a
+
+CFLAGS ?= -I$(LIBBPF_DIR)/build/usr/include/ -g
+CFLAGS += -I../headers/
+LDFLAGS ?= -L$(LIBBPF_DIR)
+
+BPF_CFLAGS ?= -I$(LIBBPF_DIR)/build/usr/include/ -I../headers/
+
+LIBS = -l:libbpf.a -lelf $(USER_LIBS)
+
+all: llvm-check $(XDP_OBJ)
+
+.PHONY: clean $(CLANG) $(LLC)
+
+clean:
+	rm -rf $(LIBBPF_DIR)/build
+	$(MAKE) -C $(LIBBPF_DIR) clean
+	rm -f $(XDP_OBJ)
+	rm -f *.ll
+	rm -f *~
+
+llvm-check: $(CLANG) $(LLC)
+	@for TOOL in $^ ; do \
+		if [ ! $$(command -v $${TOOL} 2>/dev/null) ]; then \
+			echo "*** ERROR: Cannot find tool $${TOOL}" ;\
+			exit 1; \
+		else true; fi; \
+	done
+
+$(OBJECT_LIBBPF):
+	@if [ ! -d $(LIBBPF_DIR) ]; then \
+		echo "Error: Need libbpf submodule"; \
+		echo "May need to run git submodule update --init"; \
+		exit 1; \
+	else \
+		cd $(LIBBPF_DIR) && $(MAKE) all OBJDIR=.; \
+		mkdir -p build; $(MAKE) install_headers DESTDIR=build OBJDIR=.; \
+	fi
+
+$(XDP_OBJ): %.o: %.c  Makefile $(OBJECT_LIBBPF)
+	$(CLANG) -S \
+	    -target bpf \
+	    -D __BPF_TRACING__ \
+	    $(BPF_CFLAGS) \
+	    -Wall \
+	    -Wno-unused-value \
+	    -Wno-pointer-sign \
+	    -Wno-compare-distinct-pointer-types \
+	    -Werror \
+	    -O2 -emit-llvm -c -g -o ${@:.o=.ll} $<
+	$(LLC) -march=bpf -filetype=obj -o $@ ${@:.o=.ll}
